(cl:defpackage villa_audio-srv
  (:use )
  (:export
   "REQUESTSOUNDTRANSCRIPT"
   "<REQUESTSOUNDTRANSCRIPT-REQUEST>"
   "REQUESTSOUNDTRANSCRIPT-REQUEST"
   "<REQUESTSOUNDTRANSCRIPT-RESPONSE>"
   "REQUESTSOUNDTRANSCRIPT-RESPONSE"
  ))

