// Generated by gencpp from file bwi_speech_services/RequestSoundTranscript.msg
// DO NOT EDIT!


#ifndef BWI_SPEECH_SERVICES_MESSAGE_REQUESTSOUNDTRANSCRIPT_H
#define BWI_SPEECH_SERVICES_MESSAGE_REQUESTSOUNDTRANSCRIPT_H

#include <ros/service_traits.h>


#include <bwi_speech_services/RequestSoundTranscriptRequest.h>
#include <bwi_speech_services/RequestSoundTranscriptResponse.h>


namespace bwi_speech_services
{

struct RequestSoundTranscript
{

typedef RequestSoundTranscriptRequest Request;
typedef RequestSoundTranscriptResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RequestSoundTranscript
} // namespace bwi_speech_services


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bwi_speech_services::RequestSoundTranscript > {
  static const char* value()
  {
    return "02c8de1031c790d65706e50834055714";
  }

  static const char* value(const ::bwi_speech_services::RequestSoundTranscript&) { return value(); }
};

template<>
struct DataType< ::bwi_speech_services::RequestSoundTranscript > {
  static const char* value()
  {
    return "bwi_speech_services/RequestSoundTranscript";
  }

  static const char* value(const ::bwi_speech_services::RequestSoundTranscript&) { return value(); }
};


// service_traits::MD5Sum< ::bwi_speech_services::RequestSoundTranscriptRequest> should match 
// service_traits::MD5Sum< ::bwi_speech_services::RequestSoundTranscript > 
template<>
struct MD5Sum< ::bwi_speech_services::RequestSoundTranscriptRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_speech_services::RequestSoundTranscript >::value();
  }
  static const char* value(const ::bwi_speech_services::RequestSoundTranscriptRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_speech_services::RequestSoundTranscriptRequest> should match 
// service_traits::DataType< ::bwi_speech_services::RequestSoundTranscript > 
template<>
struct DataType< ::bwi_speech_services::RequestSoundTranscriptRequest>
{
  static const char* value()
  {
    return DataType< ::bwi_speech_services::RequestSoundTranscript >::value();
  }
  static const char* value(const ::bwi_speech_services::RequestSoundTranscriptRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bwi_speech_services::RequestSoundTranscriptResponse> should match 
// service_traits::MD5Sum< ::bwi_speech_services::RequestSoundTranscript > 
template<>
struct MD5Sum< ::bwi_speech_services::RequestSoundTranscriptResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_speech_services::RequestSoundTranscript >::value();
  }
  static const char* value(const ::bwi_speech_services::RequestSoundTranscriptResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_speech_services::RequestSoundTranscriptResponse> should match 
// service_traits::DataType< ::bwi_speech_services::RequestSoundTranscript > 
template<>
struct DataType< ::bwi_speech_services::RequestSoundTranscriptResponse>
{
  static const char* value()
  {
    return DataType< ::bwi_speech_services::RequestSoundTranscript >::value();
  }
  static const char* value(const ::bwi_speech_services::RequestSoundTranscriptResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BWI_SPEECH_SERVICES_MESSAGE_REQUESTSOUNDTRANSCRIPT_H
