// Generated by gencpp from file villa_audio/RequestSoundTranscript.msg
// DO NOT EDIT!


#ifndef VILLA_AUDIO_MESSAGE_REQUESTSOUNDTRANSCRIPT_H
#define VILLA_AUDIO_MESSAGE_REQUESTSOUNDTRANSCRIPT_H

#include <ros/service_traits.h>


#include <villa_audio/RequestSoundTranscriptRequest.h>
#include <villa_audio/RequestSoundTranscriptResponse.h>


namespace villa_audio
{

struct RequestSoundTranscript
{

typedef RequestSoundTranscriptRequest Request;
typedef RequestSoundTranscriptResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RequestSoundTranscript
} // namespace villa_audio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::villa_audio::RequestSoundTranscript > {
  static const char* value()
  {
    return "02c8de1031c790d65706e50834055714";
  }

  static const char* value(const ::villa_audio::RequestSoundTranscript&) { return value(); }
};

template<>
struct DataType< ::villa_audio::RequestSoundTranscript > {
  static const char* value()
  {
    return "villa_audio/RequestSoundTranscript";
  }

  static const char* value(const ::villa_audio::RequestSoundTranscript&) { return value(); }
};


// service_traits::MD5Sum< ::villa_audio::RequestSoundTranscriptRequest> should match 
// service_traits::MD5Sum< ::villa_audio::RequestSoundTranscript > 
template<>
struct MD5Sum< ::villa_audio::RequestSoundTranscriptRequest>
{
  static const char* value()
  {
    return MD5Sum< ::villa_audio::RequestSoundTranscript >::value();
  }
  static const char* value(const ::villa_audio::RequestSoundTranscriptRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::villa_audio::RequestSoundTranscriptRequest> should match 
// service_traits::DataType< ::villa_audio::RequestSoundTranscript > 
template<>
struct DataType< ::villa_audio::RequestSoundTranscriptRequest>
{
  static const char* value()
  {
    return DataType< ::villa_audio::RequestSoundTranscript >::value();
  }
  static const char* value(const ::villa_audio::RequestSoundTranscriptRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::villa_audio::RequestSoundTranscriptResponse> should match 
// service_traits::MD5Sum< ::villa_audio::RequestSoundTranscript > 
template<>
struct MD5Sum< ::villa_audio::RequestSoundTranscriptResponse>
{
  static const char* value()
  {
    return MD5Sum< ::villa_audio::RequestSoundTranscript >::value();
  }
  static const char* value(const ::villa_audio::RequestSoundTranscriptResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::villa_audio::RequestSoundTranscriptResponse> should match 
// service_traits::DataType< ::villa_audio::RequestSoundTranscript > 
template<>
struct DataType< ::villa_audio::RequestSoundTranscriptResponse>
{
  static const char* value()
  {
    return DataType< ::villa_audio::RequestSoundTranscript >::value();
  }
  static const char* value(const ::villa_audio::RequestSoundTranscriptResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VILLA_AUDIO_MESSAGE_REQUESTSOUNDTRANSCRIPT_H
