// Auto-generated. Do not edit!

// (in-package grounded_dialogue_agent_ros.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ConductDialogueResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.command_type = null;
      this.object_location = null;
      this.destination_location = null;
      this.object_id = null;
    }
    else {
      if (initObj.hasOwnProperty('command_type')) {
        this.command_type = initObj.command_type
      }
      else {
        this.command_type = '';
      }
      if (initObj.hasOwnProperty('object_location')) {
        this.object_location = initObj.object_location
      }
      else {
        this.object_location = '';
      }
      if (initObj.hasOwnProperty('destination_location')) {
        this.destination_location = initObj.destination_location
      }
      else {
        this.destination_location = '';
      }
      if (initObj.hasOwnProperty('object_id')) {
        this.object_id = initObj.object_id
      }
      else {
        this.object_id = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ConductDialogueResult
    // Serialize message field [command_type]
    bufferOffset = _serializer.string(obj.command_type, buffer, bufferOffset);
    // Serialize message field [object_location]
    bufferOffset = _serializer.string(obj.object_location, buffer, bufferOffset);
    // Serialize message field [destination_location]
    bufferOffset = _serializer.string(obj.destination_location, buffer, bufferOffset);
    // Serialize message field [object_id]
    bufferOffset = _serializer.string(obj.object_id, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ConductDialogueResult
    let len;
    let data = new ConductDialogueResult(null);
    // Deserialize message field [command_type]
    data.command_type = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [object_location]
    data.object_location = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [destination_location]
    data.destination_location = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [object_id]
    data.object_id = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.command_type.length;
    length += object.object_location.length;
    length += object.destination_location.length;
    length += object.object_id.length;
    return length + 16;
  }

  static datatype() {
    // Returns string type for a message object
    return 'grounded_dialogue_agent_ros/ConductDialogueResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f45bd961ad31a246c98f75305c1b0442';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result
    string command_type
    string object_location
    string destination_location
    string object_id
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ConductDialogueResult(null);
    if (msg.command_type !== undefined) {
      resolved.command_type = msg.command_type;
    }
    else {
      resolved.command_type = ''
    }

    if (msg.object_location !== undefined) {
      resolved.object_location = msg.object_location;
    }
    else {
      resolved.object_location = ''
    }

    if (msg.destination_location !== undefined) {
      resolved.destination_location = msg.destination_location;
    }
    else {
      resolved.destination_location = ''
    }

    if (msg.object_id !== undefined) {
      resolved.object_id = msg.object_id;
    }
    else {
      resolved.object_id = ''
    }

    return resolved;
    }
};

module.exports = ConductDialogueResult;
