(cl:defpackage grounded_dialogue_agent_ros-msg
  (:use )
  (:export
   "<CONDUCTDIALOGUEACTION>"
   "CONDUCTDIALOGUEACTION"
   "<CONDUCTDIALOGUEACTIONFEEDBACK>"
   "CONDUCTDIALOGUEACTIONFEEDBACK"
   "<CONDUCTDIALOGUEACTIONGOAL>"
   "CONDUCTDIALOGUEACTIONGOAL"
   "<CONDUCTDIALOGUEACTIONRESULT>"
   "CONDUCTDIALOGUEACTIONRESULT"
   "<CONDUCTDIALOGUEFEEDBACK>"
   "CONDUCTDIALOGUEFEEDBACK"
   "<CONDUCTDIALOGUEGOAL>"
   "CONDUCTDIALOGUEGOAL"
   "<CONDUCTDIALOGUERESULT>"
   "CONDUCTDIALOGUERESULT"
  ))

