; Auto-generated. Do not edit!


(cl:in-package grounded_dialogue_agent_ros-msg)


;//! \htmlinclude ConductDialogueActionGoal.msg.html

(cl:defclass <ConductDialogueActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type grounded_dialogue_agent_ros-msg:ConductDialogueGoal
    :initform (cl:make-instance 'grounded_dialogue_agent_ros-msg:ConductDialogueGoal)))
)

(cl:defclass ConductDialogueActionGoal (<ConductDialogueActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ConductDialogueActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ConductDialogueActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name grounded_dialogue_agent_ros-msg:<ConductDialogueActionGoal> is deprecated: use grounded_dialogue_agent_ros-msg:ConductDialogueActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <ConductDialogueActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader grounded_dialogue_agent_ros-msg:header-val is deprecated.  Use grounded_dialogue_agent_ros-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <ConductDialogueActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader grounded_dialogue_agent_ros-msg:goal_id-val is deprecated.  Use grounded_dialogue_agent_ros-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <ConductDialogueActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader grounded_dialogue_agent_ros-msg:goal-val is deprecated.  Use grounded_dialogue_agent_ros-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ConductDialogueActionGoal>) ostream)
  "Serializes a message object of type '<ConductDialogueActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ConductDialogueActionGoal>) istream)
  "Deserializes a message object of type '<ConductDialogueActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ConductDialogueActionGoal>)))
  "Returns string type for a message object of type '<ConductDialogueActionGoal>"
  "grounded_dialogue_agent_ros/ConductDialogueActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ConductDialogueActionGoal)))
  "Returns string type for a message object of type 'ConductDialogueActionGoal"
  "grounded_dialogue_agent_ros/ConductDialogueActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ConductDialogueActionGoal>)))
  "Returns md5sum for a message object of type '<ConductDialogueActionGoal>"
  "4b30be6cd12b9e72826df56b481f40e0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ConductDialogueActionGoal)))
  "Returns md5sum for a message object of type 'ConductDialogueActionGoal"
  "4b30be6cd12b9e72826df56b481f40e0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ConductDialogueActionGoal>)))
  "Returns full string definition for message of type '<ConductDialogueActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%ConductDialogueGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: grounded_dialogue_agent_ros/ConductDialogueGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ConductDialogueActionGoal)))
  "Returns full string definition for message of type 'ConductDialogueActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%ConductDialogueGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: grounded_dialogue_agent_ros/ConductDialogueGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ConductDialogueActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ConductDialogueActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ConductDialogueActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
